// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { HealthCheckHealthGetData, HealthCheckHealthGetResponses, IngestSapSchemaSettingsSapIngestPostData, IngestSapSchemaSettingsSapIngestPostResponses, LoginAuthLoginPostData, LoginAuthLoginPostErrors, LoginAuthLoginPostResponses, SapStatusSettingsSapStatusGetData, SapStatusSettingsSapStatusGetResponses, SaveSapConnectionSettingsSapSavePostData, SaveSapConnectionSettingsSapSavePostErrors, SaveSapConnectionSettingsSapSavePostResponses, TestSapConnectionSettingsSapTestPostData, TestSapConnectionSettingsSapTestPostErrors, TestSapConnectionSettingsSapTestPostResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Health Check
 */
export const healthCheckHealthGet = <ThrowOnError extends boolean = false>(options?: Options<HealthCheckHealthGetData, ThrowOnError>): RequestResult<HealthCheckHealthGetResponses, unknown, ThrowOnError> => (options?.client ?? client).get<HealthCheckHealthGetResponses, unknown, ThrowOnError>({ url: '/health', ...options });

/**
 * Login
 */
export const loginAuthLoginPost = <ThrowOnError extends boolean = false>(options: Options<LoginAuthLoginPostData, ThrowOnError>): RequestResult<LoginAuthLoginPostResponses, LoginAuthLoginPostErrors, ThrowOnError> => (options.client ?? client).post<LoginAuthLoginPostResponses, LoginAuthLoginPostErrors, ThrowOnError>({
    url: '/auth/login',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Test Sap Connection
 */
export const testSapConnectionSettingsSapTestPost = <ThrowOnError extends boolean = false>(options: Options<TestSapConnectionSettingsSapTestPostData, ThrowOnError>): RequestResult<TestSapConnectionSettingsSapTestPostResponses, TestSapConnectionSettingsSapTestPostErrors, ThrowOnError> => (options.client ?? client).post<TestSapConnectionSettingsSapTestPostResponses, TestSapConnectionSettingsSapTestPostErrors, ThrowOnError>({
    url: '/settings/sap/test',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Save Sap Connection
 */
export const saveSapConnectionSettingsSapSavePost = <ThrowOnError extends boolean = false>(options: Options<SaveSapConnectionSettingsSapSavePostData, ThrowOnError>): RequestResult<SaveSapConnectionSettingsSapSavePostResponses, SaveSapConnectionSettingsSapSavePostErrors, ThrowOnError> => (options.client ?? client).post<SaveSapConnectionSettingsSapSavePostResponses, SaveSapConnectionSettingsSapSavePostErrors, ThrowOnError>({
    url: '/settings/sap/save',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Sap Status
 *
 * Report configuration and live SAP connectivity for the frontend.
 *
 * Never raises on SAP connection drops: every network/decryption
 * failure degrades gracefully to ``is_connected = False`` so public
 * pages keep rendering while the fallback banner takes over.
 */
export const sapStatusSettingsSapStatusGet = <ThrowOnError extends boolean = false>(options?: Options<SapStatusSettingsSapStatusGetData, ThrowOnError>): RequestResult<SapStatusSettingsSapStatusGetResponses, unknown, ThrowOnError> => (options?.client ?? client).get<SapStatusSettingsSapStatusGetResponses, unknown, ThrowOnError>({ url: '/settings/sap/status', ...options });

/**
 * Ingest Sap Schema
 *
 * Run the SAP metadata ingestion engine instantly (admin only).
 *
 * Pulls the raw OData ``$metadata`` document, regenerates the JSON
 * data dictionary under ``app/shared/sap_dictionary/`` and recompiles
 * the frontend ``apps/web/src/types/sap.d.ts`` definitions.
 */
export const ingestSapSchemaSettingsSapIngestPost = <ThrowOnError extends boolean = false>(options?: Options<IngestSapSchemaSettingsSapIngestPostData, ThrowOnError>): RequestResult<IngestSapSchemaSettingsSapIngestPostResponses, unknown, ThrowOnError> => (options?.client ?? client).post<IngestSapSchemaSettingsSapIngestPostResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/settings/sap/ingest',
    ...options
});
