// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * LoginRequest
 */
export type LoginRequest = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
};

/**
 * SAPConnectionRequest
 */
export type SapConnectionRequest = {
    /**
     * Service Layer Url
     */
    service_layer_url: string;
    /**
     * Company Db
     */
    company_db: string;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Fallback Phone Number
     */
    fallback_phone_number?: string | null;
};

/**
 * SAPIngestResponse
 *
 * Summary of a completed metadata ingestion pass.
 */
export type SapIngestResponse = {
    /**
     * Success
     */
    success: boolean;
    /**
     * Entities
     */
    entities: number;
    /**
     * Complex Types
     */
    complex_types: number;
    /**
     * Dictionary Files
     */
    dictionary_files: number;
    /**
     * Typescript File
     */
    typescript_file: string | null;
    /**
     * Detail
     */
    detail: string;
};

/**
 * SAPSaveResponse
 */
export type SapSaveResponse = {
    /**
     * Success
     */
    success: boolean;
    /**
     * Is Validated
     */
    is_validated: boolean;
    /**
     * Detail
     */
    detail: string;
};

/**
 * SAPStatusResponse
 *
 * Lightweight system status consumed by frontend fallback banners.
 */
export type SapStatusResponse = {
    /**
     * Is Validated
     */
    is_validated: boolean;
    /**
     * Is Connected
     */
    is_connected: boolean;
    /**
     * Fallback Phone Number
     */
    fallback_phone_number?: string | null;
};

/**
 * SAPTestResponse
 */
export type SapTestResponse = {
    /**
     * Success
     */
    success: boolean;
    /**
     * Detail
     */
    detail: string;
};

/**
 * TokenResponse
 */
export type TokenResponse = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type?: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type HealthCheckHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthCheckHealthGetResponses = {
    /**
     * Response Health Check Health Get
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type HealthCheckHealthGetResponse = HealthCheckHealthGetResponses[keyof HealthCheckHealthGetResponses];

export type LoginAuthLoginPostData = {
    body: LoginRequest;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type LoginAuthLoginPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginAuthLoginPostError = LoginAuthLoginPostErrors[keyof LoginAuthLoginPostErrors];

export type LoginAuthLoginPostResponses = {
    /**
     * Successful Response
     */
    200: TokenResponse;
};

export type LoginAuthLoginPostResponse = LoginAuthLoginPostResponses[keyof LoginAuthLoginPostResponses];

export type TestSapConnectionSettingsSapTestPostData = {
    body: SapConnectionRequest;
    path?: never;
    query?: never;
    url: '/settings/sap/test';
};

export type TestSapConnectionSettingsSapTestPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TestSapConnectionSettingsSapTestPostError = TestSapConnectionSettingsSapTestPostErrors[keyof TestSapConnectionSettingsSapTestPostErrors];

export type TestSapConnectionSettingsSapTestPostResponses = {
    /**
     * Successful Response
     */
    200: SapTestResponse;
};

export type TestSapConnectionSettingsSapTestPostResponse = TestSapConnectionSettingsSapTestPostResponses[keyof TestSapConnectionSettingsSapTestPostResponses];

export type SaveSapConnectionSettingsSapSavePostData = {
    body: SapConnectionRequest;
    path?: never;
    query?: never;
    url: '/settings/sap/save';
};

export type SaveSapConnectionSettingsSapSavePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SaveSapConnectionSettingsSapSavePostError = SaveSapConnectionSettingsSapSavePostErrors[keyof SaveSapConnectionSettingsSapSavePostErrors];

export type SaveSapConnectionSettingsSapSavePostResponses = {
    /**
     * Successful Response
     */
    200: SapSaveResponse;
};

export type SaveSapConnectionSettingsSapSavePostResponse = SaveSapConnectionSettingsSapSavePostResponses[keyof SaveSapConnectionSettingsSapSavePostResponses];

export type SapStatusSettingsSapStatusGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/settings/sap/status';
};

export type SapStatusSettingsSapStatusGetResponses = {
    /**
     * Successful Response
     */
    200: SapStatusResponse;
};

export type SapStatusSettingsSapStatusGetResponse = SapStatusSettingsSapStatusGetResponses[keyof SapStatusSettingsSapStatusGetResponses];

export type IngestSapSchemaSettingsSapIngestPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/settings/sap/ingest';
};

export type IngestSapSchemaSettingsSapIngestPostResponses = {
    /**
     * Successful Response
     */
    200: SapIngestResponse;
};

export type IngestSapSchemaSettingsSapIngestPostResponse = IngestSapSchemaSettingsSapIngestPostResponses[keyof IngestSapSchemaSettingsSapIngestPostResponses];
