// AUTO-GENERATED by apps/api/app/shared/ingest_sap_metadata.py
// Single source of truth for SAP Business One entity shapes.
// Do NOT edit by hand — run POST /settings/sap/ingest, the
// sync_sap_metadata_task Dramatiq actor, or
// `python -m app.shared.ingest_sap_metadata` to regenerate.
//
// This placeholder is replaced with strict `export interface` blocks
// (BusinessPartners, Invoices, ...) on the first ingestion pass against
// a validated SAP gateway.

export {};
