"""add_fallback_phone_number_to_sap_config

Revision ID: 499d3ce36b03
Revises: bb9a1e3ebc9f
Create Date: 2026-10-01 01:32:40.150934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '499d3ce36b03'
down_revision: Union[str, Sequence[str], None] = 'bb9a1e3ebc9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sapconfig', sa.Column('fallback_phone_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sapconfig', 'fallback_phone_number')
    # ### end Alembic commands ###
