"""add_sap_config_and_federated_auth

Revision ID: bb9a1e3ebc9f
Revises: d86cb054c647
Create Date: 2026-10-01 01:15:49.078265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'bb9a1e3ebc9f'
down_revision: Union[str, Sequence[str], None] = 'd86cb054c647'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sapconfig',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('service_layer_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('company_db', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_validated', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sapconfig_id'), 'sapconfig', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sapconfig_id'), table_name='sapconfig')
    op.drop_table('sapconfig')
    # ### end Alembic commands ###
